#use_frameworks!

target 'LimitInputTextControl_Example' do
  pod 'Masonry'
  pod 'LimitInputTextControl', :path => '../'

  target 'LimitInputTextControl_Tests' do
    inherit! :search_paths

    
  end
end
